spring:
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:memdb
    driver-class-name: org.h2.Driver
    username: user
    password: pwd123
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html